# Generated by Django 5.0.3 on 2024-04-04 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0003_remove_empresa_cep_remove_servico_empresa_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmpresaFuncionario",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="agenda.empresa",
                    ),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
