# Generated by Django 5.0.3 on 2024-04-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0004_empresafuncionario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empresaservico",
            name="cep",
        ),
        migrations.AddField(
            model_name="empresa",
            name="cep",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="descricao",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
