# Generated by Django 5.0.3 on 2024-04-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0006_remove_empresaservico_complemento_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empresa",
            name="cep",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="complemento",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="numero",
        ),
        migrations.AddField(
            model_name="empresaservico",
            name="cep",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="empresaservico",
            name="complemento",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="empresaservico",
            name="numero",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
