# Generated by Django 5.0.3 on 2024-04-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0007_remove_empresa_cep_remove_empresa_complemento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresaservico",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
