# Generated by Django 5.0.3 on 2024-04-04 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0009_alter_empresaservico_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="cep",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="complemento",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="numero",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servico",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="agenda.empresa",
            ),
        ),
        migrations.DeleteModel(
            name="EmpresaServico",
        ),
    ]
