# Generated by Django 5.0.3 on 2024-04-06 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0011_empresa_gerente"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenda",
            name="funcionario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agendas_funcionario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="agenda",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agendas_cliente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
