# Generated by Django 5.0.3 on 2024-04-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0014_rename_temposevico_servico_temposervico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="imagens/"),
        ),
    ]
