# Generated by Django 5.0.3 on 2024-04-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0015_alter_empresa_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="servico",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="servico",
            name="intervalo",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
