# Generated by Django 5.0.3 on 2024-04-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0016_servico_status_alter_servico_intervalo"),
    ]

    operations = [
        migrations.AddField(
            model_name="servico",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="imagens/"),
        ),
        migrations.AddField(
            model_name="user",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="imagens/"),
        ),
    ]
