# Generated by Django 5.0.3 on 2024-04-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0017_servico_foto_user_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="logradouro",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
