# Generated by Django 5.0.3 on 2024-04-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0018_empresa_logradouro"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
