# Generated by Django 5.0.3 on 2024-05-24 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0020_user_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cidade",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="empresa",
            name="cidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="agenda.cidade",
            ),
        ),
    ]
